from enum import Enum

class Cities(Enum):
    JAKARTA_SELATAN = "Jakarta Selatan"
    JAKARTA_PUSAT = "Jakarta Pusat"
    JAKARTA_BARAT = "Jakarta Barat"
    JAKARTA_TIMUR = "Jakarta Timur"
    JAKARTA_UTARA = "Jakarta Utara"
    PALEMBANG = "Palembang"
    KOTA_BOGOR = "Kota Bogor"
    KOTA_BEKASI = "Kota Bekasi"
    DEPOK = "Depok"
    KABUPATEN_BEKASI = "Kabupaten Bekasi"
    KABUPATEN_BOGOR = "Kabupaten Bogor"
    KOTA_BANDUNG = "Kota Bandung"
    KOTA_TANGERANG = "Kota Tangerang"
    TANGERANG_SELATAN = "Tangerang Selatan"
    KABUPATEN_TANGERANG = "Kabupaten Tangerang"
    YOGYAKARTA = "Yogyakarta"
    KABUPATEN_SLEMAN = "Kabupaten Sleman"
    KOTA_SEMARANG = "Kota Semarang"
    SURABAYA = "Surabaya"
    DENPASAR = "Denpasar"
    MEDAN = "Medan"
    SURAKARTA = "Surakarta/Solo"
